### ISSUE TITLE
Error sending message...

### ISSUE THREAD

**Issue by andrewbpowers** [Martin-Laclaustra/ESP8266SecureSMTP#1]
I got this error message:
"Error sending message: Could not connect to mail server: Chain could not be linked to a trust anchor.
"

:-(

**Comment by Martin-Laclaustra** [comment]
You do not provide any detail on which authentication you were using. Are you using the example?
It is a long time since I worked with this code. The certificates have probably expired.
You should try with the `SMTP.setInsecure()` option.
Also, updating the `fingerprint[]` may be necessary.
I can not devote priority to this library right now, so help is welcome in improving its development.

**Comment by jhomer** [comment]
Here is an updated fingerprint:
const uint8_t fingerprint[] = {0x94,0x44,0x97,0xD1,0xC5,0x65,0x8B,0x2F,0x9F,0xC5,0xE3,0xC3,0xCD,0x05,0x93,0xF2,0x2D,0x99,0x60,0xFC};

**Comment by Martin-Laclaustra** [comment]
@jhomer Thank you.
Did you test it? Does the library work with this? Do you want to send a pull request?

**Comment by jhomer** [comment]
I have tested with your example code and other code with this implemented in. It is working with no issues. I have never done a pull request before but I will give it a look.

**Comment by Martin-Laclaustra** [comment]
@jhomer You did it fine! The changes are merged. Thank you.
